# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnuyQ7-mSmTnruJ40fQ5HbLb39UMxfBq

To generate Transcript Of any Youtube **Video**
"""

!pip install youtube-transcript-api transformers

!pip install youtube-transcript-api

from youtube_transcript_api import YouTubeTranscriptApi

# Video ID from the YouTube URL
video_id = "82P5N2m41jE&list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH&index=13"

try:
    # Fetch the transcript in Hindi (language code 'hi')
    transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['hi'])

    # Print out the transcript
    for entry in transcript:
        print(f"{entry['start']} - {entry['duration']}: {entry['text']}")

except Exception as e:
    print(f"Error fetching transcript: {str(e)}")



"""For Summary"""

from transformers import pipeline

pipe = pipeline("summarization", model="facebook/bart-large-cnn")

pipe("""Hello, I'm Avadhesh Dubey, an enthusiastic Software Development Engineer Trainee with a passion for AI/ML and cloud technologies. I have a background in computer applications with a Master’s degree from Dr. A.P.J. Abdul Kalam Technical University, and I’m currently honing my skills at UnifyCloud.

I love solving complex problems and am particularly drawn to AI/ML applications and cloud migration strategies. I enjoy hands-on work, from building chatbots to developing web applications. I’m always eager to learn something new and embrace challenges that help me grow both personally and professionally.

In my free time, I like to explore new technologies, read about AI advancements, and work on side projects to improve my coding skills. I’m excited about the future of tech and how it can positively impact our world.""")